import re


JOB_LIMIT = 100
ACTIVE_JOB_STATUSES = {"queued", "running"}
MIN_IMAGE_DIMENSION = 16
MAX_IMAGE_DIMENSION = 4096
MAX_IMAGE_PIXELS = 3840 * 2160
MAX_EDIT_UPLOAD_BYTES = 50 * 1024 * 1024
MAX_EDIT_SOURCE_IMAGES = 16
MAX_IMAGE_COUNT = 5
DEFAULT_GALLERY_ID = "default"
DEFAULT_GALLERY_NAME = "\u9ed8\u8ba4\u753b\u5eca"
MAX_GALLERIES = 50
MAX_GALLERY_NAME_LENGTH = 60
GALLERY_UNLOCK_COOKIE = "image_cli_gallery_unlocks"
GALLERY_UNLOCK_MAX_AGE_SECONDS = 60 * 60 * 24 * 7
GALLERY_PASSWORD_HASH_ALGORITHM = "pbkdf2_sha256"
GALLERY_PASSWORD_HASH_ITERATIONS = 260_000
TRASH_MIN_RETENTION_DAYS = 1
TRASH_MAX_RETENTION_DAYS = 365
TRASH_LIMIT = 1000
DEBUG_LOG_SERVICE_SLOTS = 4
DEBUG_LOG_TYPE_SYSTEMD = "systemd"
DEBUG_LOG_TYPE_DOCKER = "docker"
DEBUG_LOG_TYPE_FILE = "file"
DEBUG_LOG_TYPES = {DEBUG_LOG_TYPE_SYSTEMD, DEBUG_LOG_TYPE_DOCKER, DEBUG_LOG_TYPE_FILE}
DEBUG_LOG_SYSTEMD_TARGET_RE = re.compile(r"^[A-Za-z0-9_.@:+-]+$")
DEBUG_LOG_DOCKER_TARGET_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.-]*$")
DEBUG_LOG_FILE_TAIL_LINES = 200
DEBUG_LOG_FILE_POLL_SECONDS = 0.75
DEBUG_LOG_FILE_MAX_PATH_LENGTH = 512
DEBUG_LOG_HEARTBEAT_SECONDS = 15.0
SUPPORTED_EDIT_IMAGE_TYPES = {"image/png", "image/jpeg", "image/webp"}
THUMBNAIL_MAX_EDGE = 1024
THUMBNAIL_QUALITY = 92
PROVIDER_API_IMAGES = "images"
PROVIDER_API_CHAT_COMPLETIONS = "chat_completions"
PROVIDER_GENERATE_MODE_GENERATE = "generate"
PROVIDER_GENERATE_MODE_COMPLETIONS = "completions"
PROVIDER_EDIT_MODE_EDIT = "edit"
PROVIDER_EDIT_MODE_COMPLETIONS = "completions"
PROVIDER_API_TYPE_ALIASES = {
    "": PROVIDER_API_IMAGES,
    "image": PROVIDER_API_IMAGES,
    "images": PROVIDER_API_IMAGES,
    "generate": PROVIDER_API_IMAGES,
    "generation": PROVIDER_API_IMAGES,
    "edit": PROVIDER_API_IMAGES,
    "image_api": PROVIDER_API_IMAGES,
    "images_api": PROVIDER_API_IMAGES,
    "chat": PROVIDER_API_CHAT_COMPLETIONS,
    "completion": PROVIDER_API_CHAT_COMPLETIONS,
    "completions": PROVIDER_API_CHAT_COMPLETIONS,
    "chat_completion": PROVIDER_API_CHAT_COMPLETIONS,
    "chat_completions": PROVIDER_API_CHAT_COMPLETIONS,
    "chat-completions": PROVIDER_API_CHAT_COMPLETIONS,
    "chat/completions": PROVIDER_API_CHAT_COMPLETIONS,
    "v1_chat_completions": PROVIDER_API_CHAT_COMPLETIONS,
}
PROVIDER_GENERATE_MODE_ALIASES = {
    "": PROVIDER_GENERATE_MODE_GENERATE,
    "image": PROVIDER_GENERATE_MODE_GENERATE,
    "images": PROVIDER_GENERATE_MODE_GENERATE,
    "generate": PROVIDER_GENERATE_MODE_GENERATE,
    "generation": PROVIDER_GENERATE_MODE_GENERATE,
    "generations": PROVIDER_GENERATE_MODE_GENERATE,
    "image_generation": PROVIDER_GENERATE_MODE_GENERATE,
    "images_generations": PROVIDER_GENERATE_MODE_GENERATE,
    "images/generations": PROVIDER_GENERATE_MODE_GENERATE,
    "chat": PROVIDER_GENERATE_MODE_COMPLETIONS,
    "completion": PROVIDER_GENERATE_MODE_COMPLETIONS,
    "completions": PROVIDER_GENERATE_MODE_COMPLETIONS,
    "chat_completion": PROVIDER_GENERATE_MODE_COMPLETIONS,
    "chat_completions": PROVIDER_GENERATE_MODE_COMPLETIONS,
    "chat-completions": PROVIDER_GENERATE_MODE_COMPLETIONS,
    "chat/completions": PROVIDER_GENERATE_MODE_COMPLETIONS,
}
PROVIDER_EDIT_MODE_ALIASES = {
    "": PROVIDER_EDIT_MODE_EDIT,
    "image": PROVIDER_EDIT_MODE_EDIT,
    "images": PROVIDER_EDIT_MODE_EDIT,
    "edit": PROVIDER_EDIT_MODE_EDIT,
    "edits": PROVIDER_EDIT_MODE_EDIT,
    "image_edit": PROVIDER_EDIT_MODE_EDIT,
    "images_edits": PROVIDER_EDIT_MODE_EDIT,
    "images/edits": PROVIDER_EDIT_MODE_EDIT,
    "chat": PROVIDER_EDIT_MODE_COMPLETIONS,
    "completion": PROVIDER_EDIT_MODE_COMPLETIONS,
    "completions": PROVIDER_EDIT_MODE_COMPLETIONS,
    "chat_completion": PROVIDER_EDIT_MODE_COMPLETIONS,
    "chat_completions": PROVIDER_EDIT_MODE_COMPLETIONS,
    "chat-completions": PROVIDER_EDIT_MODE_COMPLETIONS,
    "chat/completions": PROVIDER_EDIT_MODE_COMPLETIONS,
}
CHAT_COMPLETION_IMAGE_OMITTED_KEYS = {
    "prompt",
    "size",
    "quality",
    "output_format",
    "response_format",
}
DATA_URL_IMAGE_RE = re.compile(
    r"data:image/(?P<format>png|jpe?g|webp);base64,(?P<data>[A-Za-z0-9+/_=-]+)",
    re.IGNORECASE,
)
MARKDOWN_IMAGE_RE = re.compile(r"!\[[^\]]*\]\((?P<url>[^)\s]+)(?:\s+\"[^\"]*\")?\)")
HTTP_URL_RE = re.compile(r"https?://[^\s)\"']+")
